version: '3'
services:
  maven:
    image: maven:3.8.3-openjdk-17
    container_name: asi_maven
    volumes:
      - ../ASI-2-Atelier-1-back-FMXM-racing-team:/usr/src/mymaven
    working_dir: /usr/src/mymaven
    command: mvn clean install -DskipTests